// Code generated by goctl. DO NOT EDIT.
package types

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UserInfo struct {
	Id   int64  `path:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type UserInfoReq struct {
	Id int64 `path:"id"`
}

type UserInfoResp struct {
	Base
	Data UserInfo `json:"data"`
}

type UserInfoUpdateReq struct {
	Id int64 `json:"id"`
	UserInfo
}

type UserInfoUpdateResp struct {
	Base
}
